#C:\Projets\keycloak-angular-multi-tenant\db\SQLExplorer.properties
#May 16, 2025, 10:07:10 AM
EchoSql=false
Connect=jdbc:datadirect:openedge://localhost:20000;databaseName=KeycloakMT
AutoCommit=false
HasFetchLimit=true
ColumnWidthLimit=25
ColumnWidthMinimum=1
HasColumnLimit=false
Logging=false
EchoAll=false
SqlVerbose=false
FetchLimit=101
ReportFormat=Standard
DisableWarnings=true
Pager=false
Run=
Logfile=C:\Projets\keycloak-angular-multi-tenant\db\SQLExplorerSession.log
ConnectTimeout=180
EchoComments=false
ResultSetLimit=24
TableFormat=true
Help=
TransactionIsolation=Read Committed
PageLimit=22
Echo=true
Show=
Reset=
Disconnect=true
UseUrlFormat=false
EchoCmd=false
