client.login.model=sso
ssologin.anonymous.enabled=false
 OEPreauthfilter.enabled=true
 OEPreauthfilter.registryFile=domain_registry.bin
 OEPreauthfilter.headername=X-OE-CLIENT-CONTEXT-ID
 
 preauthAuthProvider.rolePrefix=ROLE_
 preauthAuthProvider.enabledAttrName=ATTR_ENABLED
 preauthAuthProvider.lockedAttrName=ATTR_LOCKED
 preauthAuthProvider.expiredAttrName=ATTR_EXPIRED


#OEClientPrincipalFilter.enabled=true
#OEClientPrincipalFilter.header=Authorization
#OEClientPrincipalFilter.scheme=Bearer