## login model
client.login.model=oauth2
#OEClientPrincipalFilter.passthru=false
#OEClientPrincipalFilter.forwardToken=true
#OERealm.AuthProvider.registryFile=domain_registry.bin
#OERealm.AuthProvider.multiTenant=true
 
## JWT token handler properties for jwtAuthFilter & oauth2.resSvc..
jwtToken.keystore.jwkurl= http://localhost:8080/auth/realms/fifi/protocol/openid-connect/certs
#jwtToken.usernamefield=email
#jwtToken.jwtToken.usernameField=email 
## OAuth2 Resource server configuration
oauth2.resSvc.audience=account
oauth2.resSvc.tokenServices=jwt
#jwtToken. =email
# OECORSFilter.allowAll=true
# OERealm.AuthProvider.userDomain=fifi
#OEPreauthfilter.registryFile=domain_registry.bin

