## login model
client.login.model=oauth2
#OEClientPrincipalFilter.passthru=false
#OEClientPrincipalFilter.forwardToken=true
 
## JWT token handler properties for jwtAuthFilter & oauth2.resSvc..
jwtToken.keystore.jwkurl= http://localhost:8080/auth/realms/loulou/protocol/openid-connect/certs
jwtToken.usernameField=email
## OAuth2 Resource server configuration
oauth2.resSvc.audience=account
oauth2.resSvc.tokenServices=jwt
#jwtToken. =email
# OECORSFilter.allowAll=true
# OERealm.AuthProvider.userDomain=fifi
OEClientPrincipalFilter.registryFile=domain_registry.bin


 #pas sur necesaire
OEClientPrincipalFilter.useEMailID=true

#force le domaine
#OEClientPrincipalFilter.domain=riri 
